# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('complete', models.BooleanField()),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
